<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            'New York',
            'Los Angeles',
            'Chicago',
            'Houston',
            'Phoenix',
            'Philadelphia',
            'San Antonio',
            'San Diego',
            'Dallas',
            'San Jose',
            'London',
            'Manchester',
            'Birmingham',
            'Leeds',
            'Glasgow',
            'Liverpool',
            'Sheffield',
            'Bristol',
            'Edinburgh',
            'Paris',
            'Marseille',
            'Lyon',
            'Toulouse',
            'Nice',
            'Nantes',
            'Strasbourg',
            'Montpellier',
            'Bordeaux',
            'Lille',
            'Berlin',
            'Munich',
            'Cologne',
            'Frankfurt',
            'Hamburg',
            'Dusseldorf',
            'Dortmund',
            'Essen',
            'Leipzig',
            'Dresden',
            'Madrid',
            'Barcelona',
            'Valencia',
            'Seville',
            'Bilbao',
            'Malaga',
            'Murcia',
            'Palma',
            'Las Palmas',
            'Alicante',
            'Rome',
            'Milan',
            'Naples',
            'Turin',
            'Palermo',
            'Genoa',
            'Bologna',
            'Florence',
            'Bari',
            'Catania',
            'Moscow',
            'Saint Petersburg',
            'Novosibirsk',
            'Yekaterinburg',
            'Nizhny Novgorod',
            'Kazan',
            'Chelyabinsk',
            'Omsk',
            'Samara',
            'Rostov-on-Don',
            'Tokyo',
            'Delhi',
            'Shanghai',
            'Mumbai',
            'Beijing',
            'Osaka',
            'Shenzhen',
            'Bangkok',
            'Hong Kong',
            'Jakarta',
            'Toronto',
            'Vancouver',
            'Mexico City',
            'Sao Paulo',
            'Rio de Janeiro',
            'Buenos Aires',
            'Salvador',
            'Brasilia',
            'Fortaleza',
            'Belo Horizonte',
            'Sydney',
            'Melbourne',
            'Brisbane',
            'Perth',
            'Adelaide',
            'Gold Coast',
            'Canberra',
            'Hobart',
            'Geelong',
            'Dubai',
            'Abu Dhabi',
            'Cairo',
            'Alexandria',
            'Johannesburg',
            'Cape Town',
            'Lagos',
            'Nitra',
            'Nairobi',
            'Istanbul',
            'Ankara',
            'Prague',
            'Budapest',
            'Warsaw',
            'Athens',
            'Bucharest',
            'Sofia',
            'Bratislava',
            'Ljubljana',
            'Zagreb',
            'Belgrade',
            'Amsterdam',
            'Rotterdam',
            'The Hague',
            'Utrecht',
            'Eindhoven',
            'Groningen',
            'Alkmaar',
            'Breda',
            'Arnhem',
            'Leiden',
            'Vienna',
            'Zurich',
            'Geneva',
            'Basel',
            'Bern',
            'Lausanne',
            'Lucerne',
            'St. Gallen',
            'Winterthur',
            'Schaffhausen',
            'Dublin',
            'Cork',
            'Limerick',
            'Galway',
            'Waterford',
            'Droichead Atha',
            'Swords',
            'Navan',
            'Dundalk',
            'Athlone',
            'Copenhagen',
            'Aarhus',
            'Odense',
            'Aalborg',
            'Esbjerg',
            'Randers',
            'Kolding',
            'Horsens',
            'Vejle',
            'Silkeborg',
            'Stockholm',
            'Gothenburg',
            'Malmo',
            'Uppsala',
            'Vasteras',
            'Orebro',
            'Linkoping',
            'Helsingborg',
            'Jonkoping',
            'Norrkoping',
            'Helsinki',
            'Espoo',
            'Tampere',
            'Vantaa',
            'Turku',
            'Oulu',
            'Jyvaskyla',
            'Kuopio',
            'Lahti',
            'Pori',
            'Oslo',
            'Bergen',
            'Trondheim',
            'Stavanger',
            'Kristiansand',
            'Drammen',
            'Fredrikstad',
            'Tromsø',
            'Sandefjord',
            'Lillehammer',
            'Astana',
            'Almaty',
            'Shymkent',
            'Karaganda',
            'Taraz',
            'Pavlodar',
            'Ust-Kamenogorsk',
            'Semey',
            'Aktau',
            'Atyrau',
            'Kostanay',
            'Kyzylorda',
            'Zhezkazgan',
            'Petropavl',
            'Taldykorgan',
            'Ekibastuz',
            'Ridder',
        ];

        foreach ($cities as $city) {
            City::firstOrCreate(['name' => $city]);
        }
    }
}
